apiVersion: networking.k8s.io/v1
kind: Ingress # Specifies that this resource is an Ingress, controlling external access to Services.
metadata:
  name: murphy-movies-ingress # Names this Ingress resource as "murphy-movies-ingress".
  namespace: default # Puts this resource in the "default" namespace. Adjust if needed.
  annotations:
    kubernetes.io/ingress.class: nginx # Specifies the Ingress controller (nginx) to use.
    nginx.ingress.kubernetes.io/affinity: "cookie" # Enables session affinity (sticky sessions).
    nginx.ingress.kubernetes.io/session-cookie-name: "stickounet" # Names the session cookie.
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800" # Expires in 2 days.
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800" # Max age of the cookie is also 2 days.
spec:
  rules:
    - http:
        paths:
          # 1) Direct requests to "login" to murphy-login-service
          - path: /cs122b-project5-murphy-movies/api/login # Defines the path for login requests
            pathType: Prefix # Any request beginning with /api/login/ goes here
            backend:
              service:
                name: murphy-login-service # Name of the Service to route to (matches "murphy-login.yaml")
                port:
                  number: 8080 # The port on which murphy-login-service is exposed
          - path: /cs122b-project5-murphy-movies/login # Defines the path for login html file
            pathType: Prefix
            backend:
              service:
                name: murphy-login-service # Name of the Service to route to (matches "murphy-login.yaml")
                port:
                  number: 8080 # The port on which murphy-login-service is exposed
          # 2) Direct all other requests ("/") to murphy-star-service
          - path: / # Defines the root path for all other requests
            pathType: Prefix
            backend:
              service:
                name: murphy-star-service # The Service for murphy-star
                port:
                  number: 8080 # The port on which murphy-star-service is exposed
